name: CI/CD Pipeline - Misión 1

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pruebas-y-seguridad:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar Código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pytest bandit

      - name: Pruebas Unitarias (Pytest)
        run: |
          pytest

      - name: Análisis Estático de Seguridad Python (Bandit)
        run: |
          bandit -r . -x ./.venv

      - name: Construir Imagen Docker para Análisis
        run: |
          docker build -t app-flask:test .

      - name: Análisis de Vulnerabilidades en Contenedores (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'app-flask:test'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  despliegue:
    needs: pruebas-y-seguridad
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Descargar Código
        uses: actions/checkout@v3

      - name: Desplegar por SSH a EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/despliegue_automatizado
            git pull origin main
            docker compose up -d --build